### PR TITLE
patch: Update Alpine Linux Distro link

### PR DESCRIPTION
**Pull request by vkarathanasi**

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
LGTM

**Comment by vipulgupta2048** [comment]
Closes: https://github.com/balena-io/docs/issues/1743
@klutchell I am looking at previous PR's on this repo with the same failing tests. Am I right to assume they always fail or serve some other purpose considering they are not marked as required. Do let us know.

**Comment by klutchell** [comment]
@vipulgupta2048 looks like they always fail based on previous PRs, but I've never seen this repo before so it's all new to me

**Review by vkarathanasi — COMMENTED** [review]
@balena-ci I self-certify!

**Comment by vkarathanasi** [comment]
@balena-ci I self-certify!

**Pull request merged**
